services:
  - name: database
    image: mysql:latest
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_DATABASE
        value: project_db
      - name: MYSQL_USER
        value: admin
      - name: MYSQL_PASSWORD
        value: admin
      - name: TZ
        value: Asia/Tokyo
    healthCheck:
      command: ['mysqladmin', 'ping', '-h', '127.0.0.1', '-u$$MYSQL_USER', '-p$$MYSQL_PASSWORD']

  - name: app
    buildCommand: ./src
    ports:
      - port: 5000
    dependsOn:
      - service: database
        condition: service_healthy
